{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "0c699db1-9b67-4dcf-a48a-204b798d8063",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-10 18:22:00.014 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.014 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.112 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/homebrew/Caskroom/miniforge/base/envs/quant/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-10 18:22:00.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.113 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-10 18:22:00.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-10 18:22:00.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# ==========================================\n",
    "# 📊 交互式量化投资仪表盘（Tushare Pro 版）\n",
    "# ==========================================\n",
    "import tushare as ts\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import ta\n",
    "import matplotlib.pyplot as plt\n",
    "import streamlit as st\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "# ==========================================\n",
    "# ⚙️ 初始化\n",
    "# ==========================================\n",
    "st.set_page_config(page_title=\"A股量化投资仪表盘\", layout=\"wide\")\n",
    "st.title(\"📈 A股量化投资机器学习仪表盘（Tushare Pro 版）\")\n",
    "\n",
    "# 输入 Token\n",
    "token = st.text_input(\"请输入你的 Tushare Pro Token：\", type=\"password\")\n",
    "if not token:\n",
    "    st.warning(\"请输入有效的 Tushare Token 后继续。\")\n",
    "    st.stop()\n",
    "\n",
    "ts.set_token(token)\n",
    "pro = ts.pro_api()\n",
    "\n",
    "# ==========================================\n",
    "# 🧭 用户输入\n",
    "# ==========================================\n",
    "col1, col2, col3 = st.columns(3)\n",
    "with col1:\n",
    "    stock = st.text_input(\"股票代码（如 000001.SZ）\", \"000001.SZ\")\n",
    "with col2:\n",
    "    start_date = st.text_input(\"起始日期 (YYYYMMDD)\", \"20180101\")\n",
    "with col3:\n",
    "    end_date = st.text_input(\"结束日期 (YYYYMMDD)\", \"20251101\")\n",
    "\n",
    "if st.button(\"🚀 获取并训练模型\"):\n",
    "    with st.spinner(\"正在获取数据并训练模型...\"):\n",
    "        # ① 获取行情数据\n",
    "        daily = pro.daily(ts_code=stock, start_date=start_date, end_date=end_date)\n",
    "        basic = pro.daily_basic(ts_code=stock, start_date=start_date, end_date=end_date,\n",
    "                                fields='ts_code,trade_date,pe,pb,turnover_rate,volume_ratio,total_mv')\n",
    "        df = pd.merge(daily, basic, on=['ts_code', 'trade_date'])\n",
    "        df = df.sort_values('trade_date').reset_index(drop=True)\n",
    "\n",
    "        if df.empty:\n",
    "            st.error(\"❌ 未获取到数据，请检查股票代码或权限。\")\n",
    "            st.stop()\n",
    "\n",
    "        # ② 特征工程\n",
    "        df['MA5'] = df['close'].rolling(window=5).mean()\n",
    "        df['MA20'] = df['close'].rolling(window=20).mean()\n",
    "        df['RSI'] = ta.momentum.RSIIndicator(df['close']).rsi()\n",
    "        df['MACD'] = ta.trend.MACD(df['close']).macd()\n",
    "        df['VOL5'] = df['vol'].rolling(5).mean()\n",
    "        df['RET5'] = df['close'].pct_change(5)\n",
    "        df['turnover_rate'] = pd.to_numeric(df['turnover_rate'], errors='coerce')\n",
    "        df['pe'] = pd.to_numeric(df['pe'], errors='coerce')\n",
    "        df['pb'] = pd.to_numeric(df['pb'], errors='coerce')\n",
    "        df['target'] = (df['close'].shift(-1) > df['close']).astype(int)\n",
    "        df = df.dropna()\n",
    "\n",
    "        features = ['MA5','MA20','RSI','MACD','VOL5','RET5','pe','pb','turnover_rate','volume_ratio']\n",
    "        X = df[features]\n",
    "        y = df['target']\n",
    "\n",
    "        # ③ 模型训练\n",
    "        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)\n",
    "        model = XGBClassifier(max_depth=4, n_estimators=300, learning_rate=0.05, subsample=0.8)\n",
    "        model.fit(X_train, y_train)\n",
    "        y_pred = model.predict(X_test)\n",
    "        acc = accuracy_score(y_test, y_pred)\n",
    "\n",
    "        # ④ 策略回测\n",
    "        df_test = df.iloc[len(X_train):].copy()\n",
    "        df_test['pred'] = y_pred\n",
    "        df_test['signal'] = df_test['pred'].shift(1).fillna(0)\n",
    "        df_test['return'] = df_test['close'].pct_change()\n",
    "        df_test['strategy_return'] = df_test['signal'] * df_test['return']\n",
    "\n",
    "        initial_capital = 1_000_000\n",
    "        df_test['equity_curve'] = initial_capital * (1 + df_test['strategy_return']).cumprod()\n",
    "        df_test['benchmark'] = initial_capital * (1 + df_test['return']).cumprod()\n",
    "\n",
    "        # ⑤ 绩效指标\n",
    "        total_return = df_test['equity_curve'].iloc[-1] / initial_capital - 1\n",
    "        benchmark_return = df_test['benchmark'].iloc[-1] / initial_capital - 1\n",
    "        win_rate = (df_test['strategy_return'] > 0).mean()\n",
    "        sharpe = np.mean(df_test['strategy_return']) / np.std(df_test['strategy_return']) * np.sqrt(252)\n",
    "        drawdown = (df_test['equity_curve'] / df_test['equity_curve'].cummax() - 1).min()\n",
    "\n",
    "        # ==========================================\n",
    "        # 📈 绘图\n",
    "        # ==========================================\n",
    "        st.subheader(f\"📊 策略绩效总结：{stock}\")\n",
    "        st.write(f\"✅ 模型预测准确率：{acc:.2%}\")\n",
    "        st.write(f\"策略总收益: {total_return:.2%}\")\n",
    "        st.write(f\"基准收益: {benchmark_return:.2%}\")\n",
    "        st.write(f\"胜率: {win_rate:.2%}\")\n",
    "        st.write(f\"夏普比率: {sharpe:.2f}\")\n",
    "        st.write(f\"最大回撤: {drawdown:.2%}\")\n",
    "\n",
    "        # 收益曲线图\n",
    "        fig, ax = plt.subplots(figsize=(10, 5))\n",
    "        ax.plot(df_test['trade_date'], df_test['equity_curve'], label='策略资金曲线', linewidth=2)\n",
    "        ax.plot(df_test['trade_date'], df_test['benchmark'], label='基准（买入持有）', linestyle='--')\n",
    "        ax.legend()\n",
    "        ax.set_title(f'{stock} 策略 vs 基准 收益曲线')\n",
    "        st.pyplot(fig)\n",
    "\n",
    "        # 绩效仪表盘\n",
    "        metrics = ['总收益','基准收益','胜率','夏普比率','最大回撤']\n",
    "        values = [total_return, benchmark_return, win_rate, sharpe/5, -drawdown]\n",
    "        fig2, ax2 = plt.subplots()\n",
    "        bars = ax2.bar(metrics, values, color=['#4caf50','#607d8b','#03a9f4','#ff9800','#f44336'])\n",
    "        for i, v in enumerate(values):\n",
    "            ax2.text(i, v + 0.01, f\"{v:.2%}\" if i != 3 else f\"{sharpe:.2f}\", ha='center')\n",
    "        ax2.set_title(\"策略绩效指标\")\n",
    "        st.pyplot(fig2)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "91b1c671-f987-486f-a842-f14b2963172b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (quant)",
   "language": "python",
   "name": "quant"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
